---
abstract: 'Basic Authentication for REST Client Role'
author:
  - 'Kaare Rasmussen <kaare at cpan dot net>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose: 0
  Role::REST::Client: 0.02
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200014, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Role-REST-Client-Auth-Client
requires:
  MIME::Base64: 0
  Moose::Role: 0
  perl: 5.010
resources:
  repository: git://github.com/kaare/Role-REST-Client-Auth-Client.git
version: 0.01
